In [57]:
import pandas as pd
# Average insert time (seconds)
dataSize = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = [0.0, 0.0, 0.01, 0.01, 0.02, 0.04, 0.07, 0.15, 0.29, 0.6, 1.17, 2.36, 4.89, 9.81, 19.82, 39.08, 77.93, 157.61, 327.63, 649.18, 1295.36]
HashTable = [0.01, 0.01, 0.03, 0.08, 0.24, 0.8, 3.24, 32.31, 182.22, 968.15, 4592.36, 19059.87]
BTree = [0.0, 0.01, 0.02, 0.04, 0.09, 0.2, 0.47, 1.13, 3.07, 9.04, 22.15, 51.13, 110.27, 258.02, 658.09, 20518.25]
Treap = [0.01, 0.01, 0.03, 0.06, 0.12, 0.29, 0.61, 1.43, 3.69, 9.24, 21.86, 47.64, 105.64, 229.81, 809.15, 20952.03]
SkipList = [0.0, 0.01, 0.02, 0.04, 0.08, 0.18, 0.43, 1.1, 2.94, 7.08, 17.78, 37.41, 83.77, 199.95, 406.57, 18718.11]

dictionary = {'2^k': dataSize, 'ASA': ASA, 'HashTable': HashTable, 'BTree': BTree, 'Treap': Treap, 'SkipList': SkipList}
insert_df = pd.concat([pd.Series(value, name=key) for key, value in dictionary.items()], axis=1)
insert_df

    2^k     ASA  HashTable    BTree    Treap  SkipList
0    10    0.00       0.01     0.00     0.01      0.00
1    11    0.00       0.01     0.01     0.01      0.01
2    12    0.01       0.03     0.02     0.03      0.02
3    13    0.01       0.08     0.04     0.06      0.04
4    14    0.02       0.24     0.09     0.12      0.08
5    15    0.04       0.80     0.20     0.29      0.18
6    16    0.07       3.24     0.47     0.61      0.43
7    17    0.15      32.31     1.13     1.43      1.10
8    18    0.29     182.22     3.07     3.69      2.94
9    19    0.60     968.15     9.04     9.24      7.08
10   20    1.17    4592.36    22.15    21.86     17.78
11   21    2.36   19059.87    51.13    47.64     37.41
12   22    4.89        NaN   110.27   105.64     83.77
13   23    9.81        NaN   258.02   229.81    199.95
14   24   19.82        NaN   658.09   809.15    406.57
15   25   39.08        NaN 20518.25 20952.03  18718.11
16   26   77.93        NaN      NaN      NaN       NaN
17   27  157.61        NaN      NaN      NaN       NaN
18   28  327.63        NaN      NaN      NaN       NaN
19   29  649.18        NaN      NaN      NaN       NaN
20   30 1295.36        NaN      NaN      NaN       NaN

In [19]:
import pandas as pd
# Average insert time (seconds)
dataSize = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = [0.0, 0.0, 0.01, 0.01, 0.02, 0.04, 0.07, 0.15, 0.29, 0.6, 1.17, 2.36, 4.89, 9.81, 19.82, 39.08, 77.93, 157.61, 327.63, 649.18, 1295.36]
HashTable = [0.01, 0.01, 0.03, 0.08, 0.24, 0.8, 3.24, 32.31, 182.22, 968.15, 4592.36, 19059.87]
BTree = [0.0, 0.01, 0.02, 0.04, 0.09, 0.2, 0.47, 1.13, 3.07, 9.04, 22.15, 51.13, 110.27, 258.02, 658.09, 20518.25]
Treap = [0.01, 0.01, 0.03, 0.06, 0.12, 0.29, 0.61, 1.43, 3.69, 9.24, 21.86, 47.64, 105.64, 229.81, 809.15, 20952.03]
SkipList = [0.0, 0.01, 0.02, 0.04, 0.08, 0.18, 0.43, 1.1, 2.94, 7.08, 17.78, 37.41, 83.77, 199.95, 406.57, 18718.11]

dictionary = {'2^k': dataSize, 'ASA': ASA, 'HashTable': HashTable, 'BTree': BTree, 'Treap': Treap, 'SkipList': SkipList}
insert_df = pd.concat([pd.Series(value, name=key) for key, value in dictionary.items()], axis=1)
insert_df.fillna(0,inplace=True)
insert_df

    2^k     ASA  HashTable    BTree    Treap  SkipList
0    10    0.00       0.01     0.00     0.01      0.00
1    11    0.00       0.01     0.01     0.01      0.01
2    12    0.01       0.03     0.02     0.03      0.02
3    13    0.01       0.08     0.04     0.06      0.04
4    14    0.02       0.24     0.09     0.12      0.08
5    15    0.04       0.80     0.20     0.29      0.18
6    16    0.07       3.24     0.47     0.61      0.43
7    17    0.15      32.31     1.13     1.43      1.10
8    18    0.29     182.22     3.07     3.69      2.94
9    19    0.60     968.15     9.04     9.24      7.08
10   20    1.17    4592.36    22.15    21.86     17.78
11   21    2.36   19059.87    51.13    47.64     37.41
12   22    4.89       0.00   110.27   105.64     83.77
13   23    9.81       0.00   258.02   229.81    199.95
14   24   19.82       0.00   658.09   809.15    406.57
15   25   39.08       0.00 20518.25 20952.03  18718.11
16   26   77.93       0.00     0.00     0.00      0.00
17   27  157.61       0.00     0.00     0.00      0.00
18   28  327.63       0.00     0.00     0.00      0.00
19   29  649.18       0.00     0.00     0.00      0.00
20   30 1295.36       0.00     0.00     0.00      0.00

In [58]:
import pandas as pd
# Average search time (seconds)
dataSize = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = [0.0, 0.0, 0.01, 0.02, 0.05, 0.1, 0.22, 0.48, 1.05, 2.22, 4.67, 10.18, 22.11, 46.66, 97.8, 205.05, 429.12, 925.99, 1909.61, 4024.0, 8320.88]
HashTable = [0.01, 0.02, 0.05, 0.17, 0.61, 2.31, 16.58, 86.37, 469.11, 2295.64, 10128.03, 35720.73]
BTree = [0.0, 0.01, 0.01, 0.03, 0.08, 0.17, 0.4, 0.91, 2.18, 4.83, 11.22, 24.54, 53.34, 122.49, 1092.23, 10776.65]
Treap = [0.0, 0.01, 0.01, 0.03, 0.06, 0.16, 0.38, 0.93, 2.12, 4.85, 10.94, 23.39, 51.58, 119.22, 1033.22, 10011.23]
SkipList = [0.0, 0.01, 0.01, 0.03, 0.06, 0.15, 0.35, 0.8, 1.87, 4.1, 9.33, 20.53, 44.99, 104.07, 1370.48, 11700.13]

dictionary = {'2^k': dataSize, 'ASA': ASA, 'HashTable': HashTable, 'BTree': BTree, 'Treap': Treap, 'SkipList': SkipList}
search_df = pd.concat([pd.Series(value, name=key) for key, value in dictionary.items()], axis=1)
search_df

    2^k     ASA  HashTable    BTree    Treap  SkipList
0    10    0.00       0.01     0.00     0.00      0.00
1    11    0.00       0.02     0.01     0.01      0.01
2    12    0.01       0.05     0.01     0.01      0.01
3    13    0.02       0.17     0.03     0.03      0.03
4    14    0.05       0.61     0.08     0.06      0.06
5    15    0.10       2.31     0.17     0.16      0.15
6    16    0.22      16.58     0.40     0.38      0.35
7    17    0.48      86.37     0.91     0.93      0.80
8    18    1.05     469.11     2.18     2.12      1.87
9    19    2.22    2295.64     4.83     4.85      4.10
10   20    4.67   10128.03    11.22    10.94      9.33
11   21   10.18   35720.73    24.54    23.39     20.53
12   22   22.11        NaN    53.34    51.58     44.99
13   23   46.66        NaN   122.49   119.22    104.07
14   24   97.80        NaN  1092.23  1033.22   1370.48
15   25  205.05        NaN 10776.65 10011.23  11700.13
16   26  429.12        NaN      NaN      NaN       NaN
17   27  925.99        NaN      NaN      NaN       NaN
18   28 1909.61        NaN      NaN      NaN       NaN
19   29 4024.00        NaN      NaN      NaN       NaN
20   30 8320.88        NaN      NaN      NaN       NaN

In [23]:
import pandas as pd
# Average search time (seconds)
dataSize = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = [0.0, 0.0, 0.01, 0.02, 0.05, 0.1, 0.22, 0.48, 1.05, 2.22, 4.67, 10.18, 22.11, 46.66, 97.8, 205.05, 429.12, 925.99, 1909.61, 4024.0, 8320.88]
HashTable = [0.01, 0.02, 0.05, 0.17, 0.61, 2.31, 16.58, 86.37, 469.11, 2295.64, 10128.03, 35720.73]
BTree = [0.0, 0.01, 0.01, 0.03, 0.08, 0.17, 0.4, 0.91, 2.18, 4.83, 11.22, 24.54, 53.34, 122.49, 1092.23, 10776.65]
Treap = [0.0, 0.01, 0.01, 0.03, 0.06, 0.16, 0.38, 0.93, 2.12, 4.85, 10.94, 23.39, 51.58, 119.22, 1033.22, 10011.23]
SkipList = [0.0, 0.01, 0.01, 0.03, 0.06, 0.15, 0.35, 0.8, 1.87, 4.1, 9.33, 20.53, 44.99, 104.07, 1370.48, 11700.13]

dictionary = {'2^k': dataSize, 'ASA': ASA, 'HashTable': HashTable, 'BTree': BTree, 'Treap': Treap, 'SkipList': SkipList}
search_df = pd.concat([pd.Series(value, name=key) for key, value in dictionary.items()], axis=1)
search_df.fillna(0,inplace=True)
search_df

    2^k     ASA  HashTable    BTree    Treap  SkipList
0    10    0.00       0.01     0.00     0.00      0.00
1    11    0.00       0.02     0.01     0.01      0.01
2    12    0.01       0.05     0.01     0.01      0.01
3    13    0.02       0.17     0.03     0.03      0.03
4    14    0.05       0.61     0.08     0.06      0.06
5    15    0.10       2.31     0.17     0.16      0.15
6    16    0.22      16.58     0.40     0.38      0.35
7    17    0.48      86.37     0.91     0.93      0.80
8    18    1.05     469.11     2.18     2.12      1.87
9    19    2.22    2295.64     4.83     4.85      4.10
10   20    4.67   10128.03    11.22    10.94      9.33
11   21   10.18   35720.73    24.54    23.39     20.53
12   22   22.11       0.00    53.34    51.58     44.99
13   23   46.66       0.00   122.49   119.22    104.07
14   24   97.80       0.00  1092.23  1033.22   1370.48
15   25  205.05       0.00 10776.65 10011.23  11700.13
16   26  429.12       0.00     0.00     0.00      0.00
17   27  925.99       0.00     0.00     0.00      0.00
18   28 1909.61       0.00     0.00     0.00      0.00
19   29 4024.00       0.00     0.00     0.00      0.00
20   30 8320.88       0.00     0.00     0.00      0.00

In [21]:
def calculateRatio(l):
  ratios = []
  for i in range(len(l)):
      if l[i]!=0 and i<len(l)-1:
        ratio = l[i+1] / l[i] 
        ratios.append(ratio)
  print("Average ratio:", round(sum(ratios)/len(ratios), 2))

print("{Average insert ratio}")
print("ASA")
calculateRatio(ASA)
print("---------------------")
print("HashTable")
calculateRatio(HashTable)
print("---------------------")
print("BTree")
calculateRatio(BTree)
print("---------------------")
print("Treap")
calculateRatio(Treap)
print("---------------------")
print("SkipList")
calculateRatio(SkipList)

{Average insert ratio}
ASA
Average ratio: 1.94
---------------------
HashTable
Average ratio: 4.26
---------------------
BTree
Average ratio: 4.42
---------------------
Treap
Average ratio: 3.89
---------------------
SkipList
Average ratio: 5.4

In [24]:
def calculateRatio(l):
  ratios = []
  for i in range(len(l)):
      if l[i]!=0 and i<len(l)-1:
        ratio = l[i+1] / l[i] 
        ratios.append(ratio)
  print("Average ratio:", round(sum(ratios)/len(ratios), 2))

print("{Average search ratio}")
print("ASA")
calculateRatio(ASA)
print("---------------------")
print("HashTable")
calculateRatio(HashTable)
print("---------------------")
print("BTree")
calculateRatio(BTree)
print("---------------------")
print("Treap")
calculateRatio(Treap)
print("---------------------")
print("SkipList")
calculateRatio(SkipList)

{Average search ratio}
ASA
Average ratio: 2.13
---------------------
HashTable
Average ratio: 4.18
---------------------
BTree
Average ratio: 3.27
---------------------
Treap
Average ratio: 3.24
---------------------
SkipList
Average ratio: 3.45

In [22]:
def calculateRatio(l):
  ratios = []
  for i in range(len(l)):
      if l[i]!=0 and i<len(l)-1:
        ratio = l[i+1] / l[i] 
        ratios.append(ratio)
  return round(sum(ratios)/len(ratios), 2)

for i in range(len(insert_df['HashTable'])):
    if i!=0 and insert_df['HashTable'][i] == float(0):
      insert_df['HashTable'][i] = insert_df['HashTable'][i-1] * calculateRatio(HashTable)

for i in range(len(insert_df['BTree'])):
    if i!=0 and insert_df['BTree'][i] == float(0):
      insert_df['BTree'][i] = insert_df['BTree'][i-1] * calculateRatio(BTree)

for i in range(len(insert_df['Treap'])):
    if i!=0 and insert_df['Treap'][i] == float(0):
      insert_df['Treap'][i] = insert_df['Treap'][i-1] * calculateRatio(Treap)

for i in range(len(insert_df['SkipList'])):
    if i!=0 and insert_df['SkipList'][i] == float(0):
      insert_df['SkipList'][i] = insert_df['SkipList'][i-1] * calculateRatio(SkipList)

pd.set_option('display.float_format', lambda x: '%.2f' % x)
insert_df

<ipython-input-22-d213edb0c464>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insert_df['HashTable'][i] = insert_df['HashTable'][i-1] * calculateRatio(HashTable)
<ipython-input-22-d213edb0c464>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insert_df['BTree'][i] = insert_df['BTree'][i-1] * calculateRatio(BTree)
<ipython-input-22-d213edb0c464>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insert_df['Treap'][i] = insert_df['Treap'][i-1] * calculateRatio(Treap)
<ipython-input-22-d213edb0c464>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insert_df['SkipList'][i] = insert_df['SkipList'][i-1] * calculateRatio(SkipList)

    2^k     ASA     HashTable       BTree       Treap    SkipList
0    10    0.00          0.01        0.00        0.01        0.00
1    11    0.00          0.01        0.01        0.01        0.01
2    12    0.01          0.03        0.02        0.03        0.02
3    13    0.01          0.08        0.04        0.06        0.04
4    14    0.02          0.24        0.09        0.12        0.08
5    15    0.04          0.80        0.20        0.29        0.18
6    16    0.07          3.24        0.47        0.61        0.43
7    17    0.15         32.31        1.13        1.43        1.10
8    18    0.29        182.22        3.07        3.69        2.94
9    19    0.60        968.15        9.04        9.24        7.08
10   20    1.17       4592.36       22.15       21.86       17.78
11   21    2.36      19059.87       51.13       47.64       37.41
12   22    4.89      81195.05      110.27      105.64       83.77
13   23    9.81     345890.90      258.02      229.81      199.95
14   24   19.82    1473495.22      658.09      809.15      406.57
15   25   39.08    6277089.64    20518.25    20952.03    18718.11
16   26   77.93   26740401.86    90690.66    81503.40   101077.79
17   27  157.61  113914111.93   400852.74   317048.21   545820.09
18   28  327.63  485274116.83  1771769.11  1233317.55  2947428.47
19   29  649.18 2067267737.71  7831219.46  4797605.27 15916113.75
20   30 1295.36 8806560562.62 34613990.00 18662684.49 85947014.27

In [25]:
def calculateRatio(l):
  ratios = []
  for i in range(len(l)):
      if l[i]!=0 and i<len(l)-1:
        ratio = l[i+1] / l[i] 
        ratios.append(ratio)
  return round(sum(ratios)/len(ratios), 2)

for i in range(len(search_df['HashTable'])):
    if i!=0 and search_df['HashTable'][i] == float(0):
      search_df['HashTable'][i] = search_df['HashTable'][i-1] * calculateRatio(HashTable)

for i in range(len(search_df['BTree'])):
    if i!=0 and search_df['BTree'][i] == float(0):
      search_df['BTree'][i] = search_df['BTree'][i-1] * calculateRatio(BTree)

for i in range(len(search_df['Treap'])):
    if i!=0 and search_df['Treap'][i] == float(0):
      search_df['Treap'][i] = search_df['Treap'][i-1] * calculateRatio(Treap)

for i in range(len(search_df['SkipList'])):
    if i!=0 and search_df['SkipList'][i] == float(0):
      search_df['SkipList'][i] = search_df['SkipList'][i-1] * calculateRatio(SkipList)

pd.set_option('display.float_format', lambda x: '%.2f' % x)
search_df

<ipython-input-25-8e871c5ea98e>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  search_df['HashTable'][i] = search_df['HashTable'][i-1] * calculateRatio(HashTable)
<ipython-input-25-8e871c5ea98e>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  search_df['BTree'][i] = search_df['BTree'][i-1] * calculateRatio(BTree)
<ipython-input-25-8e871c5ea98e>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  search_df['Treap'][i] = search_df['Treap'][i-1] * calculateRatio(Treap)
<ipython-input-25-8e871c5ea98e>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  search_df['SkipList'][i] = search_df['SkipList'][i-1] * calculateRatio(SkipList)

    2^k     ASA      HashTable      BTree      Treap   SkipList
0    10    0.00           0.01       0.00       0.00       0.00
1    11    0.00           0.02       0.01       0.01       0.01
2    12    0.01           0.05       0.01       0.01       0.01
3    13    0.02           0.17       0.03       0.03       0.03
4    14    0.05           0.61       0.08       0.06       0.06
5    15    0.10           2.31       0.17       0.16       0.15
6    16    0.22          16.58       0.40       0.38       0.35
7    17    0.48          86.37       0.91       0.93       0.80
8    18    1.05         469.11       2.18       2.12       1.87
9    19    2.22        2295.64       4.83       4.85       4.10
10   20    4.67       10128.03      11.22      10.94       9.33
11   21   10.18       35720.73      24.54      23.39      20.53
12   22   22.11      149312.65      53.34      51.58      44.99
13   23   46.66      624126.88     122.49     119.22     104.07
14   24   97.80     2608850.37    1092.23    1033.22    1370.48
15   25  205.05    10904994.55   10776.65   10011.23   11700.13
16   26  429.12    45582877.21   35239.65   32436.39   40365.45
17   27  925.99   190536426.74  115233.64  105093.89  139260.80
18   28 1909.61   796442263.77  376814.01  340504.20  480449.75
19   29 4024.00  3329128662.56 1232181.80 1103233.60 1657551.64
20   30 8320.88 13915757809.51 4029234.48 3574476.86 5718553.16

In [52]:
import plotly.graph_objects as go

# Add data
k = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = insert_df['ASA'].values.tolist()
HashTable = insert_df['HashTable'].values.tolist()
BTree = insert_df['BTree'].values.tolist()
Treap = insert_df['Treap'].values.tolist()
SkipList = insert_df['SkipList'].values.tolist()

fig = go.Figure()
# Create and style traces
fig.add_trace(go.Scatter(x=k, y=ASA, name='ASA',
                         line = dict(color='#2a9d8f', width=3)))
fig.add_trace(go.Scatter(x=k, y=HashTable, name='HashTable',
                         line=dict(color='#ce4257', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=BTree, name='BTree',
                         line = dict(color='#ffd166', width=3)))
fig.add_trace(go.Scatter(x=k, y=Treap, name='Treap',
                         line=dict(color='#ff9b54', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=SkipList, name='SkipList',
                         line=dict(color='#00509d', width=3, dash='dashdot')))

# Edit the layout
fig.update_layout(title='Time spent on inserting 2^k random integers (k=10, 11, 12, …, 30)',
                   xaxis_title='k',
                   yaxis_title='Time (second)')

fig.show()
fig.write_html("DS_HW3_insert_1.html")

In [51]:
import plotly.graph_objects as go

# Add data
k = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = insert_df['ASA'].values.tolist()
HashTable = insert_df['HashTable'].values.tolist()
BTree = insert_df['BTree'].values.tolist()
Treap = insert_df['Treap'].values.tolist()
SkipList = insert_df['SkipList'].values.tolist()

fig = go.Figure()
# Create and style traces
fig.add_trace(go.Scatter(x=k, y=ASA, name='ASA',
                         line = dict(color='#2a9d8f', width=3)))
fig.add_trace(go.Scatter(x=k, y=BTree, name='BTree',
                         line = dict(color='#ffd166', width=3)))
fig.add_trace(go.Scatter(x=k, y=Treap, name='Treap',
                         line=dict(color='#ff9b54', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=SkipList, name='SkipList',
                         line=dict(color='#00509d', width=3, dash='dashdot')))

# Edit the layout
fig.update_layout(title='Time spent on inserting 2^k random integers (k=10, 11, 12, …, 30)',
                   xaxis_title='k',
                   yaxis_title='Time (second)')

fig.show()
fig.write_html("DS_HW3_insert_2.html")

In [55]:
import plotly.graph_objects as go

# Add data
k = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = search_df['ASA'].values.tolist()
HashTable = search_df['HashTable'].values.tolist()
BTree = search_df['BTree'].values.tolist()
Treap = search_df['Treap'].values.tolist()
SkipList = search_df['SkipList'].values.tolist()

fig = go.Figure()
# Create and style traces
fig.add_trace(go.Scatter(x=k, y=ASA, name='ASA',
                         line = dict(color='#2a9d8f', width=3)))
fig.add_trace(go.Scatter(x=k, y=HashTable, name='HashTable',
                         line=dict(color='#ce4257', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=BTree, name='BTree',
                         line = dict(color='#ffd166', width=3)))
fig.add_trace(go.Scatter(x=k, y=Treap, name='Treap',
                         line=dict(color='#ff9b54', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=SkipList, name='SkipList',
                         line=dict(color='#00509d', width=3, dash='dashdot')))

# Edit the layout
fig.update_layout(title='Time spent on searching 2^k random integers (k=10, 11, 12, …, 30)',
                   xaxis_title='k',
                   yaxis_title='Time (second)')

fig.show()
fig.write_html("DS_HW3_search_1.html")

In [56]:
import plotly.graph_objects as go

# Add data
k = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
ASA = search_df['ASA'].values.tolist()
HashTable = search_df['HashTable'].values.tolist()
BTree = search_df['BTree'].values.tolist()
Treap = search_df['Treap'].values.tolist()
SkipList = search_df['SkipList'].values.tolist()

fig = go.Figure()
# Create and style traces
fig.add_trace(go.Scatter(x=k, y=ASA, name='ASA',
                         line = dict(color='#2a9d8f', width=3)))
fig.add_trace(go.Scatter(x=k, y=BTree, name='BTree',
                         line = dict(color='#ffd166', width=3)))
fig.add_trace(go.Scatter(x=k, y=Treap, name='Treap',
                         line=dict(color='#ff9b54', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=k, y=SkipList, name='SkipList',
                         line=dict(color='#00509d', width=3, dash='dashdot')))

# Edit the layout
fig.update_layout(title='Time spent on searching 2^k random integers (k=10, 11, 12, …, 30)',
                   xaxis_title='k',
                   yaxis_title='Time (second)')

fig.show()
fig.write_html("DS_HW3_search_2.html")